# Generated by Django 2.2.1 on 2020-03-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matlab_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileDetails',
        ),
    ]
